name: build-windows

on:
  workflow_dispatch:

env:
  RUST_VERSION: "1.75"
  FLUTTER_VERSION: "3.22.2"
  FLUTTER_RUST_BRIDGE_VERSION: "1.80.1"
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_COMMIT_ID: "9e593bb18ea69cc5095e012465dcd675a822ed0d"
  VERSION: "1.5.0"
  RENDEZVOUS_SERVER: "${{ secrets.RENDEZVOUS_SERVER }}"
  RS_PUB_KEY: "${{ secrets.RS_PUB_KEY }}"
  API_SERVER: "${{ secrets.API_SERVER }}"

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - uses: Swatinem/rust-cache@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Setup vcpkg with Github Actions binary cache
        uses: lukka/run-vcpkg@b1a0dd252f06b9e25b3c022a9a03bd7a427fb6a2
        with:
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false

      - name: Install vcpkg dependencies
        env:
          VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static
        run: |
          if ! $VCPKG_ROOT/vcpkg \
            install \
            --triplet x64-windows-static \
            --x-install-root="$VCPKG_ROOT/installed"; then
            find "${VCPKG_ROOT}/" -name "*.log" | while read -r _1; do
              echo "$_1:"
              cat "$_1"
            done
            exit 1
          fi
        shell: bash

      - name: Install flutter_rust_bridge_codegen
        run: |
          cargo install cargo-expand --version 1.0.95 --locked
          cargo install flutter_rust_bridge_codegen --version ${{ env.FLUTTER_RUST_BRIDGE_VERSION }} --features "uuid" --locked
        shell: bash

      - name: Flutter pub get
        working-directory: flutter
        run: flutter pub get

      - name: Generate bridge
        run: |
          $USERPROFILE/.cargo/bin/flutter_rust_bridge_codegen `
            --rust-input ./src/flutter_ffi.rs `
            --dart-output ./flutter/lib/generated_bridge.dart `
            --c-output ./flutter/macos/Runner/bridge_generated.h
        shell: pwsh

      - name: Build Rust
        env:
          VCPKG_ROOT: C:\vcpkg
        run: cargo build --release --features flutter
        shell: bash

      - name: Build Flutter Windows
        working-directory: flutter
        run: flutter build windows --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vegaconnect-windows-x64
          path: flutter/build/windows/x64/runner/Release/
          retention-days: 7